Try CI

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -5,15 +5,14 @@ on:
 
 name: check
 jobs:
-  check:
+  check-extension:
     runs-on: [self-hosted, dind-actions-runner]
     timeout-minutes: 25
     strategy:
       matrix:
-        node-version: [16.0, 12.17]
+        node-version: [16.0]
     env:
       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
     steps:
       - uses: actions/checkout@v2
         with:
@@ -31,47 +30,79 @@ jobs:
           echo "::endgroup::"
           
           # Build with tests
-          node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build:test --verbose
+          node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose --to-except @dxos/wallet-extension
 
-  check-storybooks:
-    runs-on: [self-hosted, dind-actions-runner]
-    timeout-minutes: 25
-    strategy:
-      matrix:
-        node-version: [16.0]
-    env:
-      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          clean: false
-      - name: Check, install and build
-        run: |
-          \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
-          npm install -g @microsoft/rush pnpm
-          sudo apt-get install -y autoconf automake make g++ libtool libxtst-dev
+          cd packages/wallet/extension
+          rushx test
+
+# jobs:
+#   check:
+#     runs-on: [self-hosted, dind-actions-runner]
+#     timeout-minutes: 25
+#     strategy:
+#       matrix:
+#         node-version: [16.0, 12.17]
+#     env:
+#       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+#       CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+#     steps:
+#       - uses: actions/checkout@v2
+#         with:
+#           fetch-depth: 0
+#           clean: false
+#       - name: Check, install and build
+#         run: |
+#           \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
+#           npm install -g @microsoft/rush pnpm
+#           sudo apt-get install -y autoconf automake make g++ libtool libxtst-dev
           
-          # Install dependencies
-          echo "::group::Install"
-          node common/scripts/install-run-rush.js install
-          echo "::endgroup::"
+#           # Install dependencies
+#           echo "::group::Install"
+#           node common/scripts/install-run-rush.js install
+#           echo "::endgroup::"
           
-          # Quick build
-          node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose
+#           # Build with tests
+#           node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build:test --verbose
 
-          # Build storybooks
-          echo "::group::Storybooks"
-          cd packages/sdk/demos && pnpm build-storybook && cd -
-          cd packages/sdk/react-ux && pnpm build-storybook && cd -
+  # check-storybooks:
+  #   runs-on: [self-hosted, dind-actions-runner]
+  #   timeout-minutes: 25
+  #   strategy:
+  #     matrix:
+  #       node-version: [16.0]
+  #   env:
+  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+  #     CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #         clean: false
+  #     - name: Check, install and build
+  #       run: |
+  #         \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
+  #         npm install -g @microsoft/rush pnpm
+  #         sudo apt-get install -y autoconf automake make g++ libtool libxtst-dev
+          
+  #         # Install dependencies
+  #         echo "::group::Install"
+  #         node common/scripts/install-run-rush.js install
+  #         echo "::endgroup::"
+          
+  #         # Quick build
+  #         node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose
 
-          # Test the demos storybooks
-          cd packages/sdk/demos
-          ./scripts/start-and-wait.sh
-          pnpm test:playwright
-          echo "::endgroup::"
-      - name: Cleanup
-        run: |
-          sudo apt-get install -y lsof
-          kill $(lsof -t -i:9001) || true
+  #         # Build storybooks
+  #         echo "::group::Storybooks"
+  #         cd packages/sdk/demos && pnpm build-storybook && cd -
+  #         cd packages/sdk/react-ux && pnpm build-storybook && cd -
+
+  #         # Test the demos storybooks
+  #         cd packages/sdk/demos
+  #         ./scripts/start-and-wait.sh
+  #         pnpm test:playwright
+  #         echo "::endgroup::"
+  #     - name: Cleanup
+  #       run: |
+  #         sudo apt-get install -y lsof
+  #         kill $(lsof -t -i:9001) || true
